import type { Metadata } from "next";
import { cookies } from "next/headers";

import 'react-toastify/dist/ReactToastify.css';
import { SessionProvider } from "@/context/SessionContext";
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function AdminLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

    const cookie = cookies();
    //console.log(cookie.get('auth_token'))
    const cookieValue = cookie.get('auth_token')

    const session = await fetch('https://mgscpz76-3000.brs.devtunnels.ms/session', {
        method: 'GET',
        headers: {
            "Content-type": 'application/json',
            Authorization: `Bearer ${cookieValue?.value}`
        },
    })

    const res = await session.json();

    console.log(res)

    if(res.error) redirect("/")

    return (
        <>
            <SessionProvider serverSession={res}>
                {children}
            </SessionProvider>
        </>
    );
}
