import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import { cookies } from "next/headers";

import 'react-toastify/dist/ReactToastify.css';
import { SessionProvider } from "@/context/SessionContext";
import { Session } from '../context/SessionContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  const cookie = cookies();
  //console.log(cookie.get('auth_token'))
  const cookieValue = cookie.get('auth_token')

  const session = await fetch('https://mgscpz76-3000.brs.devtunnels.ms/session', {
    method: 'GET',
    headers: {
      "Content-type": 'application/json',
      Authorization: `Bearer ${cookieValue?.value}`
    },
  })

  const res = await session.json();

  return (
    <html lang="en">
      <body className={inter.className}>

        <ToastContainer theme="dark" position="bottom-right" />
        <SessionProvider serverSession={res}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
