import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import { cookies } from "next/headers";

import 'react-toastify/dist/ReactToastify.css';
import { SessionProvider } from "@/context/SessionContext";
import { Session } from '../context/SessionContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={inter.className}>

        <ToastContainer theme="dark" position="bottom-right" />
        {children}
      </body>
    </html>
  );
}
